# Generated by Django 3.0.6 on 2020-05-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
