# Generated by Django 3.0.6 on 2020-06-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200520_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='password',
            new_name='place',
        ),
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.CharField(default='', max_length=120),
        ),
    ]
