# Generated by Django 3.0.6 on 2020-06-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200606_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='menuid',
            field=models.CharField(default='', max_length=120),
        ),
    ]
