# Generated by Django 3.0.6 on 2020-06-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_article_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='postid',
            field=models.CharField(max_length=120),
        ),
    ]
