# Generated by Django 3.0.6 on 2020-05-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='civnum',
            field=models.CharField(default='civnum', max_length=15, unique=True, verbose_name='Civnum'),
        ),
        migrations.AddField(
            model_name='user',
            name='phnum',
            field=models.CharField(default='phnum', max_length=15, unique=True, verbose_name='Phnum'),
        ),
    ]
