# Generated by Django 3.0.6 on 2020-06-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.CharField(max_length=20)),
                ('menuid', models.CharField(default='', max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('place', models.CharField(max_length=120)),
                ('price', models.CharField(default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
